### ISSUE TITLE
The move-selected-text-right's action is strange.

### ISSUE THREAD

**Issue by ton-katsu** [t9md/atom-vim-mode-plus-move-selected-text#1]
![xun8hoolvy](https://cloud.githubusercontent.com/assets/838767/13548163/0190f4d6-e32d-11e5-8c59-bced282dc754.gif)

Step
1. Select entire line by cmd-l.
2. move-selected-text-right by ctrl-l

Plugin Version
vim-mode-plus@0.23.0
vim-mode-plus-move-selected-text@0.4.1

Keymap
Only keymap example of atom-vim-mode-plus-move-selected-text

Atom version
1.5.4

**Comment by t9md** [comment]
I cannot reproduce it. And test spec covers this case.
So need further information.

happen everytime or occasional?
Right direction only?
Editor is softwrapped?
Remove all keymap and set ONLY move-selected-text-right then still happen?
Check keymap resolver to check keymap issue.

**Comment by t9md** [comment]
I notice slight cursor position diff and from it I understand what the cause is.
You must be using `cmd-l` to select-line. Use `V` instead.
`cmd-l` is mapped to `editor:select-line` and vmp can't handle outer vmp command correctly.

To solve your issue. use `V` instead of `cmd-l` or set keymap for `cmd-l` to `activate-linewise-visual-mode`.

**Comment by ton-katsu** [comment]
I understood.
Thank you.
